package com.sales.system.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class SellerAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSellerAllPropertiesEquals(Seller expected, Seller actual) {
        assertSellerAutoGeneratedPropertiesEquals(expected, actual);
        assertSellerAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSellerAllUpdatablePropertiesEquals(Seller expected, Seller actual) {
        assertSellerUpdatableFieldsEquals(expected, actual);
        assertSellerUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSellerAutoGeneratedPropertiesEquals(Seller expected, Seller actual) {
        assertThat(actual)
            .as("Verify Seller auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSellerUpdatableFieldsEquals(Seller expected, Seller actual) {
        assertThat(actual)
            .as("Verify Seller relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getLastName()).as("check lastName").isEqualTo(expected.getLastName()))
            .satisfies(a -> assertThat(a.getEmployeeCode()).as("check employeeCode").isEqualTo(expected.getEmployeeCode()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSellerUpdatableRelationshipsEquals(Seller expected, Seller actual) {
        // empty method
    }
}
